### ISSUE TITLE
Upgrade packages to address security issues

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/tg-show-runner#4]
Trygve, could you run `npm audit` on this package and check out the security issues that it presents. I know we're only running this on our local network, but it would be good to update a few things to ensure that we're not creating problems down the road.

**Comment by bryankennedy** [comment]
You can also see the package issues here:
https://github.com/scimusmn/tg-show-runner/network/alerts

**Comment by tnordberg** [comment]
Have not had a chance to address this yet. Is lower priority, but still need to address.

**Comment by tnordberg** [comment]
Created a `security-audit` branch and was able to eliminate 76 vulnerabilities. The 4 remaining are specific to webpack and after spending some time on it I'm realizing it will take much more time to manually untangle. Leaving those for now. Still need to update and test in Theater.

**Comment by tnordberg** [comment]
Looking clean: https://github.com/scimusmn/tg-show-runner/network/alerts
Updated on theater PC and tested.
